import type { Metadata } from 'next'

import { Geist, Geist_Mono } from 'next/font/google'

import './globals.css'
import Header from '@/components/navigation/header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen w-screen overflow-x-hidden antialiased`}
      >
        <div className="bg-background mx-auto flex h-full min-h-screen flex-col gap-10  overflow-x-hidden pt-9">
          <div className="px-9">
            <Header />
          </div>
          <div className="relative h-full">{children}</div>
        </div>
      </body>
    </html>
  )
}
